// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> greet() => RustLib.instance.api.crateApiGreet();

Future<String> getConfigFromRust() =>
    RustLib.instance.api.crateApiGetConfigFromRust();

Stream<String> startTsConnection(
        {required String ip, required int port, required String apiKey}) =>
    RustLib.instance.api
        .crateApiStartTsConnection(ip: ip, port: port, apiKey: apiKey);

Future<void> sendTsMessage({required String payload}) =>
    RustLib.instance.api.crateApiSendTsMessage(payload: payload);

Future<String> requestTsApiKey({required String ip, required int port}) =>
    RustLib.instance.api.crateApiRequestTsApiKey(ip: ip, port: port);

Future<String> connectQuery(
        {required String ip,
        required int port,
        required String user,
        required String pass}) =>
    RustLib.instance.api
        .crateApiConnectQuery(ip: ip, port: port, user: user, pass: pass);

Future<String> querySendCommand({required String command}) =>
    RustLib.instance.api.crateApiQuerySendCommand(command: command);

Future<void> queryDisconnect() =>
    RustLib.instance.api.crateApiQueryDisconnect();

Future<void> toggleRustDebugLog(
        {required bool enabled, required String path}) =>
    RustLib.instance.api
        .crateApiToggleRustDebugLog(enabled: enabled, path: path);
